<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-01[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP01.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-02[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP02.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-03[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP03.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-04[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP04.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-05[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP05.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-06[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP06.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-07[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP07.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-08[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP08.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-09[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP09.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-10[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP10.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-11[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP11.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-12[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP12.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-13[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP13.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-14[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP14.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-15[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP15.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-16[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP16.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-17[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP17.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-18[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP18.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-19[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP19.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-20[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP20.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-21[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP21.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-22[/COLOR]</title>
<link>https://h7w5x5e6.map2.ssl.hwcdn.net/RCServer14/ondemand/SWATT01EP22.mp4?attachment=true</link>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

