<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-01[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP01.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-02[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP02.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-03[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP03.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-04[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP04.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-05[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP05.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-06[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP06.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-07[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP07.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-08[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP08.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-09[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP09.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-10[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP10.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-11[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP11.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-12[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP12.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-13[/COLOR]</title>
<link>https://baixarvideo.azureedge.net/RCServer14/ondemand/SWATT03EP13.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>


