<item>
<title>[COLOR lime]S.W.A.T[/COLOR] [COLOR deeppink]DUBLADO[/COLOR] [COLOR white]EP-01[/COLOR]</title>
<link>https://d3msohyhy1sovs.cloudfront.net/RCServer14/ondemand/SWATT03EP01.mp4?attachment=true</link>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu.</info>
</itam>

