<channels>
<channel>
<name>[COLOR deeppink] <<<<<<<< [/COLOR] [COLOR lime]1-TP-S.W.A.T[/COLOR] [COLOR deeppink] >>>>>>>> [/COLOR]</name>
<thumbnail>https://ia601402.us.archive.org/34/items/24_20201023/21.jpg</thumbnail>
<externallink>https://raw.githubusercontent.com/sillas200/AGUIAPLAYH/main/1-TP-S.W.A.T</externallink>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/26.jpg</fanart>
<info>

"[COLOR lime]- AS MELHORES SERIES -[/COLOR]"</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

<channels>
<channel>
<name>[COLOR deeppink] <<<<<<<< [/COLOR] [COLOR lime]2-TP-S.W.A.T[/COLOR] [COLOR deeppink] >>>>>>>> [/COLOR]</name>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/22.jpg</thumbnail>
<externallink>https://raw.githubusercontent.com/sillas200/AGUIAPLAYH/main/2-TP-S.W.A.T</externallink>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/25.jpg</fanart>
<info>

"[COLOR lime]- AS MELHORES SERIES -[/COLOR]"</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

<channels>
<channel>
<name>[COLOR deeppink] <<<<<<<< [/COLOR] [COLOR lime]3-TP-S.W.A.T[/COLOR] [COLOR deeppink] >>>>>>>> [/COLOR]</name>
<thumbnail>https://ia801402.us.archive.org/34/items/24_20201023/24.jpg</thumbnail>
<externallink>https://raw.githubusercontent.com/sillas200/AGUIAPLAYH/main/3-TP-S.W.A.T</externallink>
<fanart>https://ia801402.us.archive.org/34/items/24_20201023/27.jpg</fanart>
<info>

"[COLOR lime]- AS MELHORES SERIES -[/COLOR]"</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


